### ISSUE TITLE
Ubuntu jammy not supported yet in install.sh

### ISSUE THREAD

**Issue by rootchick** [Libki/libki-server#283]
**Describe the bug**
I see that ubuntu jammy (22.04) isn't supported yet by install.sh.  Is there a reason for it or have you just not included it yet?  I'm happy to help test--I use the contents of install.sh as a basis for writing ansible playbooks for installing Libki.

**Deployment architecture:**
 - OS: Ubuntu 22.04 (server edition)
 - Deployment style: LAMP
 - Versions of software used

**Comment by kylemhall** [comment]
@loidor maintains that script. Assigning.

**Comment by pescew** [comment]
fwiw I have successfully installed and used libki server on ubuntu 22.04 after modifying the install script.  So I don't think it's a matter of incompatibility, just a matter of updating the install script.

**Comment by kylemhall** [comment]
@rootchick I just took a crack at updating install.sh, let me know if it works! I don't have anything running ubuntu to test it again atm. If you find any package names have changed let me know and I'll get them updated!

**Comment by rootchick** [comment]
Thank you, will do!  I'm not actually using it, I just used the contents for writing ansible playbooks for installing.  But if I find any package names  that need changing I'll let you know.  I'm working on writing a version to install multiple instances (didn't notice the existing playbooks in the repo until I was almost done so I decided to keep going), and I am running into an issue where update_db.pl is getting hung up because after the first instance is created it can't access /tmp/libki_metrics, which looks like it's created by Libki.pm.  Should I be doing something differently?  This is the bit of ansible code I'm using for running update_db.pl:

```
  - name: run the libki database installer
    shell: export PERL5LIB=$PERL5LIB:/home/{{ item.name }}/libki-server/lib && perl /home/{{ item.name }}/libki-server/installer/update_db.pl 
    args:
      executable: /bin/bash
    become_user: "{{ item.name }}"
    with_items: "{{ libki_servers }}"
```

Apologies if it's inappropriate to ask this here.
