### ISSUE TITLE
Webhooks for login/logout events

### ISSUE THREAD

**Issue by jfmartinezm** [Libki/libki-server#347]
In our system, when a user logs in, Libki should send a notification to an external system to perform additional tasks. This notification has to be sent over HTTP to a certain endpoint.

This feature could be implemented by creating a new module which contains the notification code (similar to /lib/Libki/LDAP.pm or SIP.pm), and calling it on successful login/logout.

**Comment by kylemhall** [comment]
It sounds like you want webhooks for Libki logins. Can you tell me what kind of data that webhook would need to transmit?

**Comment by jfmartinezm** [comment]
In this particular case, our system needs to get the username, the password and the ip address of the client. But maybe the webhook could allow to choose what information should be sent, with some kind of configuration setting, eg:

```yaml
---
- webhook: http://server/endpoint
  attributes_to_send:
    - username
    - password
    - client.ipaddress
``` 
This way, the webhook system could be used to send different information to different endpoints, and perhaps on different events (login, logout, client registration, etc).
